# Generated by Django 4.2.23 on 2025-08-15 18:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReadOnly',
            fields=[
            ],
            options={
                'verbose_name': 'Group View',
                'verbose_name_plural': 'Groups View',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
